<?xml version="1.0"?>

<robot  xmlns:xacro= "http://www.ros.org/wiki/xacro"
	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	name="robot_xacro">

	<xacro:include filename="$(find marrtino_description)/urdf/marrtino_robot.gazebo"/>

    	<xacro:property name="M_PI" value="3.14159265359"/>

	<!-- Box Properties -->
	<xacro:property name="base_x_size" value="0.28"/>
	<xacro:property name="base_y_size" value="0.37"/>
	<xacro:property name="base_z_size" value="0.21"/>

  <!-- Wheel Mounting Positions -->
	<!--
	<xacro:property name="wheel_radius" value="0.07"/>
  <xacro:property name="wheel_lenght" value="0.03"/>
  <xacro:property name="castor_radius" value="0.03"/>
  <xacro:property name="castor_length" value="0.015"/>
  -->

	<!-- Wheel Properties -->
	<xacro:property name="wheel_radius" value="0.07"/>
  <xacro:property name="wheel_lenght" value="0.03"/>
  <xacro:property name="castor_radius" value="0.03"/>
  <xacro:property name="castor_length" value="0.015"/>

	<xacro:macro name="default_inertial" params = "mass">
		<inertial>
			<mass value="${mass}" />
			<inertia ixx="1.0" ixy = "0.0" ixz = "0.0"
				 iyy="1.0" iyz = "0.0" izz = "1.0" />
		</inertial>
	</xacro:macro>


<!-- ..........................................Links definitions .....................................................-->

	<link name="base_footprint"/>

	<link name="base_link">
		<visual>
			<geometry>
				<box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
			</geometry>
			<origin xyz="0 0 ${base_z_size/2}" rpy = "0 0 0" />
			<material name="red">
				<color rgba="1 0 0 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<box size="${base_x_size} ${base_y_size} ${base_z_size}"/> <!--<box size="0.36 0.44 0.21"/>-->
			</geometry>
			<origin xyz="0 0 ${base_z_size/2}" rpy = "0 0 0" />
		</collision>
		<xacro:default_inertial mass="5"/>
	</link>

	<link name="left_wheel_link">
		<visual>
			<geometry>
				<cylinder length="${wheel_lenght}" radius="${wheel_radius}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
			<material name="black">
				<color rgba="0 0 0 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${wheel_lenght}" radius="${wheel_radius}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
		</collision>
		<xacro:default_inertial mass="0.5"/>
	</link>

	<link name="right_wheel_link">
		<visual>
			<geometry>
				<cylinder length="${wheel_lenght}" radius="${wheel_radius}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
			<material name="black">
				<color rgba="0 0 0 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${wheel_lenght}" radius="${wheel_radius}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
		</collision>
		<xacro:default_inertial mass="0.5"/>
	</link>

	<link name="block" type="fixed">
		<visual>
			<geometry>
				<box size="0.03 0.03 0.10"/>
			</geometry>
			<origin xyz="0 0 -0.05" rpy = "0 0 0"/>
			<material name="red">
				<color rgba="1 0 0 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<box size="0.03 0.03 0.10"/>
			</geometry>
			<origin xyz="0 0 -0.05" rpy = "0 0 0"/>
		</collision>
		<xacro:default_inertial mass="0.1"/>
	</link>

	<link name="castor_link">
		<visual>
			<geometry>
				<cylinder length="${castor_length}" radius="${castor_radius}"/>
			</geometry>
			<origin rpy="${M_PI/2} 0 0" xyz="0 0 0"/>
			<material name="black">
				<color rgba="0 0 0 1"/>
			</material>
		</visual>
		<collision>
			<geometry>
				<cylinder length="${castor_length}" radius="${castor_radius}"/>
			</geometry>
			<origin rpy="${M_PI/2} 0 0" xyz="0 0 0"/>
		</collision>
		<xacro:default_inertial mass="0.25"/>
	</link>

	<!-- Hokuyo Laser -->
	<link name="laser" >
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://marrtino_description/meshes/hokuyo.dae"/>
			</geometry>
		</visual>

		<collision>
			<origin rpy="0 0 0" xyz="0 0 0"/>
			<geometry>
				<box size="0.1 0.1 0.1"/>
			</geometry>
		</collision>

		<xacro:default_inertial mass="0.1"/>
	</link>

<!-- ..........................................Joints definitions .....................................................-->

	<joint name="left_wheel_joint" type="continuous">
		<parent link="base_link" />
		<child link="left_wheel_link" />
		<origin xyz="0.10 0.20 -0.03" rpy="0 0 0"/>
		<axis xyz="0 1 0" />
	</joint>

	<joint name="right_wheel_joint" type="continuous">
		<parent link="base_link" />
		<child link="right_wheel_link" />
		<origin xyz="0.10 -0.20 -0.03" rpy="0 0 0"/>-->
		<axis xyz="0 1 0" />
	</joint>

	<joint name="castor_joint" type="continuous">
		<parent link="block" />
		<child link="castor_link" />
		<origin xyz="0 0 -0.085" rpy="0 0 0"/>-->
		<axis xyz="0 1 0" />
	</joint>

	<joint name="block_to_base_joint" type="fixed">
		<parent link="base_link" />
		<child link="block" />
		<origin xyz="-0.085 0.0 0.0" rpy="0 0 0"/>
		<axis xyz="0 1 0" />
	</joint>

  <joint name="base_footprint_joint" type="fixed">
		<parent link="base_footprint" />
		<child link="base_link" />
		<origin xyz="0.0 0.0 ${wheel_radius + 0.03}" rpy="0 0 ${M_PI}"/>
		<axis xyz="0 1 0" />
	</joint>

	<!--  Laser joint -->
	<joint name="base_laser" type="fixed">
		<parent link="base_link"/>
		<child link="laser"/>
		<origin xyz="-0.115 0 ${base_z_size}" rpy="0 0 ${M_PI}"/>
		<axis xyz="0 1 0"/>
	</joint>

</robot>
